services:
  db:
    image: mysql:5.7
    networks:
      - wp_net
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresspassword

  wordpress:
    image: wordpress:latest
    ports:
      - "8085:80"
    networks:
      - wp_net
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpresspassword
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db

networks:
  wp_net:
    driver: bridge

volumes:
  db_data:
