services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpassword

  redis:
    image: redis:alpine

  app:
    image: nextcloud:latest
    ports:
      - "8087:80"
    volumes:
      - nextcloud_data:/var/var/html
    environment:
      - MYSQL_PASSWORD=nextcloudpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

volumes:
  db_data:
  nextcloud_data:
